import {Outfit } from "next/font/google";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./_components/Header";

const outfit = Outfit({subsets:["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="px-3 px-md-5">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
